### ISSUE TITLE
How to prevent nuxt upgrade when installing nuxt-seo-kit

### ISSUE THREAD

**Issue by ClineResearch** [harlan-zw/nuxt-seo-kit#128]
### Details

Hi !
We use nuxt@3.4.3 
When we want to install @nuxt-seo-kit, nuxt package is automatically upgrade toward the latest release (3.8.0).
How can we prevent this?
Thanks.
JF

**Comment by davidstackio** [comment]
Confirming that this behavior happens. In my case I was planning on upgrading to nuxt@latest anyway, but it would be nice if there was at least a warning that it will do so. Or better yet, it doesn't force an upgrade of Nuxt as per OP's comment.

**Comment by harlan-zw** [comment]
Hmm, this definitely shouldn't be the behavior, not sure why that would be the case. The only dependency that may trigger it is nuxt/kit :thinking: 

Will investigate further when I have a chance. Thanks for the issue.

**Comment by ClineResearch** [comment]
Ok! 
Keep me informed.
Thanks.

**Comment by harlan-zw** [comment]
Seems like the most likely candidate for this bug was one of the modules using `@vueuse/nuxt` which has a dependency constraint on the latest Nuxt version. 

It has been [fixed](https://github.com/vueuse/vueuse/commit/866a1d8180dc63a9d8ab6a4ea963edccbf806c56) in the `main` branch, once a release is out it should be solved going forwards.
